# Based on a build template from:
#
# https://docs.haskellstack.org/en/stable/travis_ci/

# Choose a build environment
dist: xenial

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    sources:
      - sourceline: 'ppa:jonathonf/texlive-2018'
    packages:
      - libgmp-dev
      - texlive-fonts-recommended
      - texlive-generic-extra
      - texlive-latex-extra
      - texlive-luatex
      - texlive-publishers
      - texlive-science
      - texlive-xetex
      - latexmk
      - fonts-lmodern
      - fonts-texgyre
      - python-pygments

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

jobs:
  include:
    - stage: lens
      script: stack --no-terminal install lens
    - stage: deps
      script: stack --no-terminal --install-ghc test --only-dependencies
    - stage: build
      script:
      - export IDDQD=1
      - stack --no-terminal test --haddock --no-haddock-deps
    - stage: notes
      script:
      - stack exec tex-plots
      - export PUB_DATE=$(date '+%Y-%m-%dT%H:%M:%S%z')
      - sed -i -e "s/PUBDATE/${PUB_DATE}/" notes/notes.tex
      - sed -i -e "s/{{PUB_DATE}}/${PUB_DATE}/" gh-pages/index.html
      - pushd notes; make; popd
      - cp notes/notes.pdf gh-pages/notes.pdf
      - cp logo.svg gh-pages/logo.svg

stages:
  - lens
  - deps
  - build
  - notes

# Deploy necessary components to GitHub Pages
deploy:
  provider: pages
  local_dir: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
