resolver: nightly-2019-03-09
packages:
- .
extra-deps:
- iterm-show-0.1.0.1
- diagrams-postscript-1.4.1
- tasty-hedgehog-0.2.0.0
- github: lancelet/haskell-chart
  commit: 609ba441e55bc1925dd0845ab23a3e8971a34e94
  subdirs:
  - chart
  - chart-diagrams